name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Deploy with Terraform
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve

    - name: Generate Ansible Inventory
      run: |
        terraform output instance_ip > ansible_inventory

    - name: Run Ansible Playbook
      run: ansible-playbook -i ansible_inventory ./ansible/provisionar.yml
